name: Build Full Installer ISO/DMG image

on:
  workflow_dispatch:
    inputs:
      macos_version:
        description: "Choose a macOS version to build."
        required: true
        type: choice
        options:
          - ''
          - 'Tahoe'
          - 'Sequoia'
          - 'Sonoma'
          - 'Ventura'
          - 'Monterey'
          - 'Big Sur'
          - 'Catalina'
          - 'Mojave'
          - 'High Sierra'
          - 'Sierra'
          - 'El Capitan'
          - 'Yosemite'
          - 'Mavericks'
          - 'Mountain Lion'
          - 'Lion'

      image_format:
        description: "Choose 'iso' for virtual machines, 'dmg' for flash to USB drive."
        required: true
        type: choice
        options:
          - ''
          - 'iso'
          - 'dmg'

jobs:
  preflight:
    if: ${{ inputs.macos_version != '' && inputs.image_format != '' }}
    runs-on: ubuntu-slim
    timeout-minutes: 5

    outputs:
      _build: ${{ steps.check.outputs._build }}

    steps:
      - name: Preflight
        id: check
        run: |
          echo "_build=true" >> $GITHUB_OUTPUT

          echo "## Preflight check passed" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Starting macOS image build." >> "$GITHUB_STEP_SUMMARY"

  build-macos-image:
    needs: preflight
    if: needs.preflight.outputs._build == 'true'

    runs-on: macos-15-intel
    timeout-minutes: 80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: System Information
        run: |
          echo "Runner OS: $(sw_vers -productName) $(sw_vers -productVersion)"
          echo "Architecture: $(uname -m)"
          echo ""

          df -h $(mktemp)

          echo ""
          echo "RAM: $(top -l 1 | grep PhysMem)"

          echo ""
          echo "CPU: $(sysctl -n machdep.cpu.brand_string)"

      - name: Create macOS image
        id: create_image
        run: |
          chmod +x ./mkmaciso

          ./mkmaciso "${{ inputs.macos_version }}" "${{ inputs.image_format }}"

          if [ "${{ inputs.image_format }}" == "iso" ]; then
            echo "image_name=$(basename *.iso)" >> $GITHUB_OUTPUT
          else
            echo "image_name=$(basename *.dmg.img)" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.create_image.outputs.image_name }}
          compression-level: 0
          retention-days: 15
          archive: false

      - name: Summary
        if: always()
        run: |
          sum() {
            printf '%s\n' "$@" >> "$GITHUB_STEP_SUMMARY"
          }

          if [ "${{ steps.create_image.outcome }}" == "failure" ]; then

            sum "## Download macOS failed" \
                "" \
                "> [!WARNING]" \
                "> This runner may have network issues. Please re-run the workflow."

          elif [ "${{ job.status }}" == "success" ]; then

            if [ "${{ inputs.image_format }}" == "iso" ]; then

              sum "## Successfully built $(basename *.iso)" \
                  "" \
                  "> [!Important]" \
                  "> This ISO image is intended for creating macOS virtual machines on Proxmox VE, QEMU, and VMware."

            else

              sum "## Successfully built $(basename *.dmg.img)" \
                  "" \
                  "> [!Important]" \
                  "> This DMG image is intended for flashing to USB drive using Rufus (Windows) or dd (Linux)."

            fi

            sum "" \
                "> [!TIP]" \
                "> Enable Cloudflare WARP for faster download from GitHub artifact."

          fi
